version: '3'
services:

  db_myapp:
    container_name: db_myapp
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 112233
      POSTGRES_USER: db_myapp
      POSTGRES_DB: db_myapp
    networks:
      - nw_db_myapp
    volumes:
      - "vl_myapp_data:/var/lib/postgresql/data"

  service-myapp:
    container_name: service_myapp
    restart: always
    build: ./web/
    ports:
     - "3333:8000"
    volumes:
      - ./web:/usr/src/app
    networks:
      - nw_db_myapp
    command: >
      bash -c "
        python manage.py migrate && 
        gunicorn web.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db_myapp

networks:
  nw_db_myapp:

volumes:
  vl_myapp_data: